apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: sklearn
spec:
  name: iris
  predictors:
  - graph:
      children: []
      implementation: SKLEARN_SERVER
      modelUri: <<FILL IN>>
      name: classifier
    name: default
    replicas: 1
  volumes:
    name: host-mount
    hostpath:
      path: <<FILL IN>>